### ISSUE TITLE
Landing page image/hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Anthropology#1]
We will need a fresh hero image for this program, all of their current photos on their DreamWeaver site are old and crumby. Please and thank you.

**Comment by pixelyunicorn** [comment]
Pinging @ZMcGroarty

**Comment by ZMcGroarty** [comment]
![hero_anthro-min](https://cloud.githubusercontent.com/assets/15017242/24207644/d14cc7e4-0ef7-11e7-98f2-524fce2553d3.png)

**Comment by CVE82** [comment]
This looks amazing Zac, thank you!
