### ISSUE TITLE
Hero image

### ISSUE THREAD

**Issue by saracurnow** [TULiberalArts/Anthropology#10]
We received feedback from the department and one of the requests is that the hero image be changed. Full request below.

"The first issue is the photo on the home page. It rather reinforces a very old fashioned and colonialist view of anthropology as dealing with 'Other' and 'Primitive' peoples, rather than modern populations. It HAS to GO. I have included in the attached zip file an image from the current website that looks more 'normal' but there are others on there you could use perhaps (some I don't like as the same criticism could be made." 

The image he suggested won't work due to its dimensions, but I've attached it here (at least I think I have) to give an idea of what he would prefer.

Thanks!

![anthropology image](https://user-images.githubusercontent.com/26552028/28583173-37ec9718-7136-11e7-82cd-ef621d5d9d62.JPG)

**Comment by ZMcGroarty** [comment]
Hey all,

Who is the contact for Anthro? I want to find them a new image but the one they provided is super low-res. I was going to share with them our stock website and perhaps they can help me find something that fits their needs.

Thanks,
Zac

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu>





On Jul 25, 2017, at 12:44 PM, saracurnow <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #10<https://github.com/TULiberalArts/Anthropology/issues/10> to @ZMcGroarty<https://github.com/zmcgroarty>.

**Comment by ZMcGroarty** [comment]
It’s Paul Farnsworth. For now, can we leave that space blank (or just do a solid color)?

--
Zach Epstein
Director, Marketing and Communications
College of Liberal Arts
Temple University

1114 W. Berks St. | 835 Anderson Hall
Philadelphia, PA 19122
215-204-6243
zepstein@temple.edu<mailto:zepstein@temple.edu>

On Jul 25, 2017, at 1:13 PM, Zachary McGroarty <tug28959@temple.edu<mailto:tug28959@temple.edu>> wrote:

Hey all,

Who is the contact for Anthro? I want to find them a new image but the one they provided is super low-res. I was going to share with them our stock website and perhaps they can help me find something that fits their needs.

Thanks,
Zac

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu/>





On Jul 25, 2017, at 12:44 PM, saracurnow <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #10<https://github.com/TULiberalArts/Anthropology/issues/10> to @ZMcGroarty<https://github.com/zmcgroarty>.

**Comment by ZMcGroarty** [comment]
Yeah if we remove the image, it defaults to red.

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu>





On Jul 25, 2017, at 1:21 PM, Zach Epstein <tug28445@temple.edu<mailto:tug28445@temple.edu>> wrote:

It’s Paul Farnsworth. For now, can we leave that space blank (or just do a solid color)?

--
Zach Epstein
Director, Marketing and Communications
College of Liberal Arts
Temple University

1114 W. Berks St. | 835 Anderson Hall
Philadelphia, PA 19122
215-204-6243
zepstein@temple.edu<mailto:zepstein@temple.edu>

On Jul 25, 2017, at 1:13 PM, Zachary McGroarty <tug28959@temple.edu<mailto:tug28959@temple.edu>> wrote:

Hey all,

Who is the contact for Anthro? I want to find them a new image but the one they provided is super low-res. I was going to share with them our stock website and perhaps they can help me find something that fits their needs.

Thanks,
Zac

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu/>





On Jul 25, 2017, at 12:44 PM, saracurnow <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #10<https://github.com/TULiberalArts/Anthropology/issues/10> to @ZMcGroarty<https://github.com/zmcgroarty>.

**Comment by CVE82** [comment]
Just removed the hero image
