### ISSUE TITLE
List of broken links for grant resources 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Anthropology#13]
The following links are broken in the Grant Resource section. 

- http://councilforeuropeanstudies.org/grants-and-awards/grants-and-awards-faq 
- http://www.amphilsoc.org/grants
- http://www.leakeyfoundation.org/grants/overview
- http://www.nps.gov/history/hps/abpp 
- http://www.usip.org/grants-fellowships/fellowship-opportunities/jennings-randolph-peace-scholarship-dissertation-program 
- http://www.wtgrantfoundation.org/funding_opportunities/research_grants
- http://www.temple.edu/grad/calendar/

**Comment by saltedbones** [comment]
thanks
