### ISSUE TITLE
Keywords on home page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Anthropology#16]
Can you please send me the keywords that were on the homepage, I need them for a document going to Central regarding our programs.

**Comment by saltedbones** [comment]
Can you clarify? The keywords were added by Sarah/Zach and made no sense. You mean keywords as in keywords and meta description, correct? There was nonsensical stuff in that field.

**Comment by CVE82** [comment]
Yes the keywords on the homepage before the description. I will leave that blank then in the document I send if there are no current ones.

**Comment by saltedbones** [comment]
I can give you some updated ones, want me to? It will take a few minutes.

**Comment by CVE82** [comment]
That would be super thank you, no rush if you can't do it today. I can always submit them separately to Ron tomorrow.

**Comment by saltedbones** [comment]
just give me a min....

**Comment by saltedbones** [comment]
Temple Department of Anthropology, PhD in Anthropology, Major in Anthropology, Minor in Anthropology
