### ISSUE TITLE
Please resize and center hero image

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Anthropology#18]
The body is all in, thanks for getting the image set!

**Comment by ZMcGroarty** [comment]
Let me know if this works

![hero_anthro-min](https://user-images.githubusercontent.com/15017242/33896859-ef900788-df31-11e7-9760-80fda527a54e.png)

**Comment by CVE82** [comment]
Thank you! Waiting on Chris to fix a build issue and then I will restart!
