### ISSUE TITLE
Add dashes to phone # in footer

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Anthropology#4]
Can we add dashes so it reads 215-204-7577? I couldn't remember where in GitHub the footer is stored, but I can change things like this myself if you point me in the right direction.

**Comment by tu-chill** [comment]
![screen shot 2017-04-05 at 10 53 13 am](https://cloud.githubusercontent.com/assets/12816361/24711481/1a3b738c-19ee-11e7-9111-30411d4a7d6a.png)

**Comment by tu-chill** [comment]
Values for Footer address and phone number can be updated in the _config.yml

![screen shot 2017-04-05 at 10 53 53 am](https://cloud.githubusercontent.com/assets/12816361/24711666/9b1524c6-19ee-11e7-801d-390dd5745488.png)
