### ISSUE TITLE
Add hero image

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Anthropology#5]
Homepage just needs an image to replace the red block.

**Comment by CVE82** [comment]
The hero image has been added, @ZMcGroarty can you please resize the image for us so the Statue of Liberty is centered? Thanks!

**Comment by ZMcGroarty** [comment]
Will do, thanks!



On Tue, Apr 18, 2017 at 9:50 AM -0400, "Camille Elliott" <notifications@github.com<mailto:notifications@github.com>> wrote:


The hero image has been added, @ZMcGroarty<https://github.com/ZMcGroarty> can you please resize the image for us so the Statue of Liberty is centered? Thanks!

**Comment by CVE82** [comment]
Awesome thanks!
