### ISSUE TITLE
Meta-data Content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Anthropology#7]
The home page needs:

meta-description: 100 or so words
meta-keywords: 3 or 4 unique for this page

**Comment by saracurnow** [comment]
Descriptions finished

**Comment by CVE82** [comment]
Hey we still need a few keywords and descriptions, here are the pages:

Faculty- Keywords
Graduate- Description 
Research Labs- Keywords
Resources- Description

**Comment by CVE82** [comment]
These are done.
